### ISSUE TITLE
Инициализировать docker/docker compose/Makefile в проекте

### ISSUE THREAD

**Issue by khoshov** [khoshov/dubplate-special#12]
```
version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A config worker -B -l INFO
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: nodemon --watch ./ --ext scss --ignore webpack_bundles --exec "npx webpack --config webpack.config.js --watch"
    volumes:
      - ./assets:/usr/src/app/assets
      - ./webpack.config.js:/usr/src/app/webpack.config.js
      - ./.stylelintrc.json:/usr/src/app/.stylelintrc.json
      - ./.prettierrc:/usr/src/app/.prettierrc
      - ./webpack-stats.json:/usr/src/app/webpack-stats.json
      - /usr/src/app/node_modules
```

```
PYTHON := docker-compose run -u $(USERID):$(GROUPID) --rm django python
CELERY := docker-compose run -u $(USERID):$(GROUPID) --rm celery python
NODE := docker-compose run -u $(USERID):$(GROUPID) --rm node
NPM := $(NODE) npm

up:
	docker-compose up

down:
	docker-compose down

build:
	docker-compose build

build-no-cache:
	docker-compose build --no-cacheFROM python:3.9

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app/

COPY requirements.txt .

RUN pip install -U pip
RUN pip install -r requirements.txt

COPY . `.`

collectstatic:
	$(PYTHON) manage.py collectstatic --noi -c

startapp:
	$(PYTHON) manage.py startapp ${app}

makemigrations:
	$(PYTHON) manage.py makemigrations ${app}

migrate:
	$(PYTHON) manage.py migrate ${app}

createsuperuser:
	$(PYTHON) manage.py createsuperuser

shell:
	$(PYTHON) manage.py shell_plus

celery:
	$(CELERY) manage.py shell_plus

reset_db:
	$(PYTHON) manage.py reset_db

npm_install:
	$(NPM) i

npm_list:
	$(NPM) ls

npm_root:
	$(NPM) root -g

npm_install_dev:
	$(NPM) i ${package} --save-dev

node_shell:
	$(NODE) node

update:
	$(NPM) update

```

FROM python:3.9

ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app/

COPY requirements.txt .

RUN pip install -U pip
RUN pip install -r requirements.txt

COPY . .
