### ISSUE TITLE
Настроить деплой тестового стенда

### ISSUE THREAD

**Issue by khoshov** [khoshov/dubplate-special#43]
По ssh при мердже в develop обновляем проект на виртуалке и перезапускаем (применяем миграции собираем статику и тд)

**Comment by Pryanik0071** [comment]
```yaml
name: Deploy to Dev. server

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SERVER_HOST }}
        username: ${{ secrets.DEV_SSH_USERNAME }}
        key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.DEV_PROJECT_PATH }}
          git pull origin develop
            
          uv sync --no-dev
          uv run manage.py migrate
          uv run manage.py compilemessages
          
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          
          echo "Deployment successful!"
```

Нужно создать пользователя на сервере (или взять текущего) и прописать ему ssh ключ и записать в secrets проекта.
